---
terrain_page_size:
  help: |
    The size of each page of the texture in meters.
  type: integer
  default: 1000
terrain_page_resolution:
  help: |
    The size of each page of the texture in pixels.
  type: integer
  default: 512
terrain_num_patches:
  help: |
    The number of tesselated patches on the side of the planet.  Thus if this
    number is `n` the total number of patches is `(n-1)^2`.
  type: integer
  default: 200
terrain_num_pages:
  help: |
    The number of pages of fine data maintained on a side in the paged textures.
    Thus if this number is `n` the total number of pages is `n^2`.
  type: integer
  default: 5
...
