---
terrain_page_size:
  help: |
    The size of each page of the texture in meters.
  type: integer
  default: 100
terrain_page_resolution:
  help: |
    The size of each page of the texture in pixels.
  type: integer
  default: 1024
terrain_num_patches:
  help: |
    The number of tesselated patches on the side of the planet.  Thus if this
    number is `n` the total number of patches is `(n-1)^2`.
  type: integer
  default: 300
terrain_num_pages:
  help: |
    The number of pages of fine data maintained on a side in the paged textures.
    Thus if this number is `n` the total number of pages is `n^2`.
  type: integer
  default: 3
sky_integration_steps:
  help: |
    Indicates the accuracy of the sky integration system.  Typical values are from 
    10 to 100.
  type: integer
  default: 10
building_clump_count:
  help: |
    The number of building clumps or villages in the world.
  type: integer
  default: 50
building_clump_min_size:
  help: |
    The minimum number of building in a clump.
  type: integer
  default: 4
building_clump_max_size:
  help: |
    The maximum number of building in a clump.
  type: integer
  default: 25
forest_tree_count:
  help:
    The maximum number of trees in the world.  Fewer trees will be more sparsely
    distributed.
  type: integer
  default: 4000000
npc_count:
  help:
    The number of non-player-characters in the world
  type: integer
  default: 50
earth_radius:
  help:
    As on the box
  type: float
  default: 6.36e6
atmosphere_radius:
  help:
    As on the box
  type: float
  default: 6.42e6
...
